import type {
  ComponentInternalInstance,
  RendererElement,
  VNode,
  VNodeArrayChildren,
} from "@soppy-vue/runtime-dom"
import {
  cloneVNode,
  Fragment,
  getCurrentInstance,
  onBeforeUnmount,
  onMounted,
  toRaw,
} from "@soppy-vue/runtime-dom"
import type { MaybeArray } from "@soppy-vue/shared"
import { ensureArray, isFunction, PatchFlags, ShapeFlags, syncRunFns } from "@soppy-vue/shared"
import { isKeepAlive } from "./keepAlive"
import { isSameVNodeType } from "../../vnode"
import type { ComponentOptions } from "../options"

/* ==================== base utils ==================== */
const enterCallback: unique symbol = Symbol("__sv_enterCallback")
const leaveCallback: unique symbol = Symbol("__sv_leaveCallback")

interface TransitionState {
  isMounted: boolean
  // transform flag
  isLeaving: boolean
  isUnmounting: boolean
  /**
   * light: track vnode pending leave so they can be force-removed
   * when a new vnode with the same key enters before the leave
   * animation finishes.
   *
   * @example
   * ```vue
   * <transition>
   *   <!--
   *     when text changing, there will be two
   *     p with the same key in real DOM tree
   *   -->
   *   <p :key="fixed">{{ text }}</p>
   * </transition>
   * ```
   *
   * maintain a { vnode.type, { key: vnode } } cache
   */
  leavingVNodes: Map<any, Record<string, VNode>>
}

type PendingCallback = (cancelled?: boolean) => void
interface TransitionTarget {
  [enterCallback]?: PendingCallback
  [leaveCallback]?: PendingCallback
}

const useTransitionState = () => {
  const state: TransitionState = {
    isMounted: false,
    isLeaving: false,
    isUnmounting: false,
    leavingVNodes: new Map(),
  }
  onMounted(() => (state.isMounted = true))
  onBeforeUnmount(() => (state.isUnmounting = true))
  return state
}

const getTransitionRawChildren = (children: VNode[], parentKey?: VNode["key"]): VNode[] => {
  const result: VNode[] = []
  let keyedFragmentCount = 0

  for (let i = 0; i < children.length; i++) {
    const child = children[i]

    const key =
      parentKey == null
        ? // this branch goes unkeyed children process?
          child.key
        : /**
           * key for this branch is never null, which
           * generated by `parentKey` + `childKey`
           */
          String(parentKey) + String(child.key != null ? child.key : i)

    /**
     * light: handle scenarios with fragment child by
     * flattening `Fragment.children` into result
     */
    if (child.type === Fragment) {
      if (child.patchFlag & PatchFlags.KEYED_FRAGMENT) {
        keyedFragmentCount++
      }
      result.push(...getTransitionRawChildren(child.children as VNode[], key))
    } else if (child.type !== Comment) {
      result.push(key != null ? cloneVNode(child, { key }) : child)
    }
  }

  if (keyedFragmentCount > 1) {
    for (let i = 0; i < result.length; i++) {
      /**
       * light: because Fragment inside was flattened, the vnode tree
       * struct changed, so we had to revert children to full diff
       */
      result[i].patchFlag = PatchFlags.BAIL
    }
  }
  return result
}

export type { TransitionState }
export { useTransitionState, getTransitionRawChildren }

/* ==================== keep alive utils ==================== */
/**
 * note: vue@3.4 has limited support for `Teleport` in `Transition`
 * in `getInnerChild`, it is introduced in 3.5 and later, our impl
 * withdraw the support for `Teleport`
 */
const getInnerChild = (vnode: VNode): VNode | undefined => {
  if (!isKeepAlive(vnode)) return vnode
  if (vnode.component) return vnode.component.subTree

  const { shapeFlag, children } = vnode

  if (children) {
    if (shapeFlag & ShapeFlags.ARRAY_CHILDREN) {
      return (children as VNodeArrayChildren)[0] as VNode
    }

    if (shapeFlag & ShapeFlags.SLOTS_CHILDREN && isFunction((children as any).default)) {
      return (children as any).default()
    }
  }
}

/**
 * origin comment: handles special case: KeepAlive in the case of a
 * KeepAlive in a leave phase we need to return a KeepAlive placeholder
 * with empty content to avoid the KeepAlive instance from being unmounted.
 */
const emptyPlaceholder = (vnode: VNode): VNode | undefined => {
  if (isKeepAlive(vnode)) {
    vnode = cloneVNode(vnode)
    vnode.children = null
    return vnode
  }
}

/* ==================== hooks utils ==================== */
// exposed by vnode.transition, which we manipulated actually
interface TransitionHooks<HostElement = RendererElement> {
  mode: BaseTransitionProps["mode"]
  beforeEnter(el: HostElement): void
  enter(el: HostElement): void
  leave(el: HostElement, remove: () => void): void
  // clone hooks from transition vnode
  clone(vnode: VNode): TransitionHooks<HostElement>
  /**
   * optional hooks, dynamically injected in `setup` based on mode
   * - out-in: afterLeave
   * - in-out: delayLeave, delayedLeave
   */
  afterLeave?(): void
  delayLeave?(el: HostElement, earlyRemove: () => void, delayedLeave: () => void): void
  delayedLeave?(): void
}

function getLeavingNodesByType(state: TransitionState, vnode: VNode) {
  const { leavingVNodes } = state
  let leavingVNodesCache = leavingVNodes.get(vnode.type)
  if (!leavingVNodesCache) {
    // ensure leavingVNodesCache existed
    leavingVNodes.set(vnode.type, (leavingVNodesCache = Object.create(null)))
  }
  return leavingVNodesCache!
}

function resolveTransitionHooks(
  vnode: VNode,
  props: BaseTransitionProps<any>,
  state: TransitionState,
  instance: ComponentInternalInstance
) {
  const {
    mode,
    onBeforeEnter,
    onEnter,
    onAfterEnter,
    onEnterCancelled,

    onBeforeLeave,
    onLeave,
    onAfterLeave,
    onLeaveCancelled,
  } = props
  const key = String(vnode.key)
  const leavingVNodesCache = getLeavingNodesByType(state, vnode)

  /**
   * note: `invoke*` below are internel fns of `BaseTransition`,
   * `Transition` should impl them on its own
   */
  const invokeHook = <T extends any[] = [el: any]>(
    hooks: MaybeArray<(...args: T) => void> | undefined,
    args: T
  ) => hooks && syncRunFns(ensureArray(hooks), args)

  const invokeHookAutoDone = (
    hook: MaybeArray<(el: any, done: () => void) => void>,
    args: [TransitionTarget, () => void]
  ) => {
    invokeHook(hook, args)
    // auto done
    const done = args[1]
    ensureArray(hook).every((hook) => hook.length <= 1) && done()
  }

  const hooks: TransitionHooks<TransitionTarget> = {
    mode,
    beforeEnter(el) {
      if (!state.isMounted) return

      if (el[leaveCallback]) {
        el[leaveCallback](true /* cancelled */)
      }
      const leavingVNode = leavingVNodesCache[key]

      if (
        leavingVNode &&
        isSameVNodeType(vnode, leavingVNode) &&
        (leavingVNode.el as TransitionTarget)[leaveCallback]
      ) {
        ;(leavingVNode.el as TransitionTarget)[leaveCallback]!()
      }
      invokeHook(onBeforeEnter, [el])
    },
    enter(el) {
      if (!state.isMounted) return

      let called = false
      const done = (el[enterCallback] = (cancelled?) => {
        if (called) return
        called = true

        if (cancelled) {
          invokeHook(onEnterCancelled, [el])
        } else {
          invokeHook(onAfterEnter, [el])
        }

        if (hooks.delayedLeave) {
          hooks.delayedLeave()
        }

        el[enterCallback] = undefined
      })

      return onEnter ? invokeHookAutoDone(onEnter, [el, done]) : done()
    },
    leave(el, remove) {
      if (el[enterCallback]) {
        el[enterCallback](true /* cancelled */)
      }

      if (state.isUnmounting) {
        return remove()
      }

      invokeHook(onBeforeLeave, [el])

      let called = false
      const key = String(vnode.key)
      leavingVNodesCache[key] = vnode

      const done = (el[leaveCallback] = (cancelled?) => {
        if (called) return
        called = true

        remove()
        if (cancelled) {
          invokeHook(onLeaveCancelled, [el])
        } else {
          invokeHook(onAfterLeave, [el])
        }
        el[leaveCallback] = undefined
        if (leavingVNodesCache[key] === vnode) {
          delete leavingVNodesCache[key]
        }
      })

      return onLeave ? invokeHookAutoDone(onLeave, [el, done]) : done()
    },
    clone(vnode) {
      return resolveTransitionHooks(vnode, props, state, instance)
    },
  }
  return hooks
}

function injectTransitionHooks(vnode: VNode, hooks: TransitionHooks) {
  if (vnode.shapeFlag & ShapeFlags.COMPONENT && vnode.component) {
    /**
     * light: transition hooks injection in component, using recursive
     * injection to hanle nested components
     */
    injectTransitionHooks(vnode.component.subTree, hooks)
  }
  // always set vnode.trainsition, ignored suspense impl
  vnode.transition = hooks
}

export type { TransitionHooks }
export { resolveTransitionHooks, injectTransitionHooks }

/* ==================== BaseTransition impl ==================== */
interface BaseTransitionProps<HostElement = RendererElement> {
  mode?: "in-out" | "out-in" | "default"
  // enter
  onBeforeEnter?: MaybeArray<(el: HostElement) => void>
  onEnter?: MaybeArray<(el: HostElement, done: () => void) => void>
  onAfterEnter?: MaybeArray<(el: HostElement) => void>
  onEnterCancelled?: MaybeArray<(el: HostElement) => void>
  // leave
  onBeforeLeave?: MaybeArray<(el: HostElement) => void>
  onLeave?: MaybeArray<(el: HostElement, done: () => void) => void>
  onAfterLeave?: MaybeArray<(el: HostElement) => void>
  onLeaveCancelled?: MaybeArray<(el: HostElement) => void>
  // not-impl: not planning to impl appear
}

/**
 * note: actually, the validator is useless because our impl of `resolvePropValue`
 * does not perform validation, however, to ensure consistency with the official
 * vue, we retain this struct
 */
const TransitionHookValidator = [Function, Array]
const BaseTransitionPropsValidators = {
  mode: String,

  onBeforeEnter: TransitionHookValidator,
  onEnter: TransitionHookValidator,
  onAfterEnter: TransitionHookValidator,
  onEnterCancelled: TransitionHookValidator,

  onBeforeLeave: TransitionHookValidator,
  onLeave: TransitionHookValidator,
  onAfterLeave: TransitionHookValidator,
  onLeaveCancelled: TransitionHookValidator,
}

const BaseTransitionImpl: ComponentOptions = {
  name: "Transition",
  props: BaseTransitionPropsValidators,

  setup(props: BaseTransitionProps, { slots }) {
    const instance = getCurrentInstance()!
    const state = useTransitionState()
    return () => {
      /* =============== prepare: child & props =============== */
      const children = slots.default && getTransitionRawChildren(slots.default())
      if (!children || children.length === 0) return

      /**
       * self-design: exclude COMMENT node in `getTransitionRawChildren`,
       * so the child is the first non-comment child exactly.
       */
      const child = children[0]

      // origin comment: there's no need to track reactivity for these props so use the raw
      const rawProps = toRaw(props)
      const mode = rawProps.mode

      /* =============== process: inject hooks =============== */
      if (state.isLeaving) {
        return emptyPlaceholder(child)
      }

      const innerChild = getInnerChild(child)
      if (!innerChild) {
        return emptyPlaceholder(child)
      }
      const enterHooks = resolveTransitionHooks(innerChild, rawProps, state, instance)
      injectTransitionHooks(innerChild, enterHooks)

      const oldInnerChild = instance.subTree && getInnerChild(instance.subTree)

      /**
       * not-impl: vue@3.5 remove the handling of `transitionKeyChanged`,
       * it is recommended users bind dynamic keys rather than maintaining
       * a second set of keys internally
       */
      if (oldInnerChild && !isSameVNodeType(innerChild, oldInnerChild)) {
        const leavinghooks = resolveTransitionHooks(oldInnerChild, rawProps, state, instance)
        injectTransitionHooks(oldInnerChild, leavinghooks)

        if (mode === "out-in") {
          // mode: old leave first -> new enter next
          state.isLeaving = true
          leavinghooks.afterLeave = () => {
            state.isLeaving = false
            if (instance.update.active !== false) {
              instance.effect.dirty = true
              instance.update()
            }
          }
          return emptyPlaceholder(child)
        } else if (mode === "in-out") {
          // mode: new enter first -> old leave next
          leavinghooks.delayLeave = (el: TransitionTarget, earlyRemove, delayedLeave) => {
            const leavingVNodesCache = getLeavingNodesByType(state, oldInnerChild)

            leavingVNodesCache[String(oldInnerChild.key)] = oldInnerChild

            el[leaveCallback] = () => {
              earlyRemove()
              el[leaveCallback] = undefined
              delete enterHooks.delayedLeave
            }
            enterHooks.delayedLeave = delayedLeave
          }
        }
      }

      return child
    }
  },
}

const BaseTransition = BaseTransitionImpl as unknown as {
  new (): { $props: BaseTransitionProps<any>; $slots: { default(): VNode[] } }
}

export type { BaseTransitionProps }
export { BaseTransition, BaseTransitionPropsValidators }
