# tsup required
allowBuilds:
  esbuild: true
  puppeteer: true

packages:
  - "packages/*"
  - "scripts/*"
  - "internals/*"

# follow vue's design, use `catalog` to
# centrally manage package version
catalog:
  vite: "^8.2.2"
  vitest: "^4.1.11"
  tsup: "^8.5.1"
