import { isArray, isObject, isString, ShapeFlags } from "@soppy-vue/shared"
import type { Data } from "./component"
import { RuntimeFlags } from "./constant"
import type { RendererNode } from "./renderer"

/**
 * origin vue accept many types, even `VNode`. this happens in cases like
 * @example <component :is="vnode"/>
 */
const Text = Symbol.for("sv-text")
export { Text }

type VNodeTypes = string | typeof Text

type VNodeProps = {
  key?: string | number | symbol
}

type VNodeKey = string | number | symbol | null

type VNodeChildAtom = VNode | string | number | boolean | null | undefined

// light: allow nested array as vnode.children
type VNodeArrayChildren = (VNodeArrayChildren | VNodeChildAtom)[]
type VNodeChild = VNodeChildAtom | VNodeArrayChildren

type VNodeNormalizedChildren = string | VNodeArrayChildren | null

export type { VNodeArrayChildren, VNodeChild, VNodeNormalizedChildren, VNodeKey }

/**
 * origin vue implementation is as follows:
 * addons explanation:
 *  - `HostElement`: related to implementation of `teleport`, `transition`
 *  - `ExtraProps`: extends prop defination via `props: (VNodeProps & ExtraProps) | null`
 */
interface VNode<HostNode = RendererNode, ExtraProps = { [key: string]: any }> {
  [RuntimeFlags.IS_VNODE]: true
  type: VNodeTypes
  // ensure `props.class` can accepted
  props: (VNodeProps & ExtraProps) | null
  children: VNodeNormalizedChildren
  component: any

  /**
   * light: diff requires
   * - el: store real dom object
   * - key: for diff processing
   */
  el: HostNode | null
  key: VNodeKey

  // optimize runtime
  shapeFlag: number
  patchFlag: number
}

/**
 * mainly used for render, function as follows:
 * - ensure child is vnodes
 * - auto-wrap children array with Fragment
 */
function normalizeVNode(child: VNodeChild): VNode {
  if (isObject(child)) {
    return child as VNode
  } else {
    return createVNode(Text, null, String(child))
  }
}

function normalizeChildren(vnode: VNode, children: unknown) {
  let type
  const { shapeFlag } = vnode
  if (children == null) {
    children = null
  } else if (isArray(children)) {
    type = ShapeFlags.ARRAY_CHILDREN
  } else if (isObject(children)) {
    if (shapeFlag & ShapeFlags.ELEMENT) {
      const slot = (children as any).default
      if (slot) {
        normalizeChildren(vnode, slot())
      }
    } else {
      // process `children = slot()` here, return text for now
      children = String(children)
      type = ShapeFlags.TEXT_CHILDREN
    }
  } else {
    children = String(children)
    type = ShapeFlags.TEXT_CHILDREN
  }

  vnode.children = children as VNodeNormalizedChildren
  vnode.shapeFlag |= type
}

const normalizeKey = ({ key }: VNodeProps): VNode["key"] => (key != null ? key : null)

function createBaseVNode(
  type: VNodeTypes,
  props: (Data & VNodeProps) | null,
  children: unknown = null,
  shapeFlag: number,
  patchFlag: number
): VNode {
  const vnode = {
    [RuntimeFlags.IS_VNODE]: true,
    type,
    props,
    children,
    key: props && normalizeKey(props),
    el: null,
    component: null,
    shapeFlag,
    patchFlag,
  } as VNode

  /**
   * for runtime optimization, vue exposes `creatElementVNode` and `creatVNode` method
   * to compiler and developers. essentially, by controlling `needFullChildrenNormalization`,
   * - vue allows compiler to generate code that can quickly performs `normalizeChildren`.
   * - vue dosen't trust the vnode tree generated by developers via `createVNode`, thus must normalize the whole vnode tree
   */
  normalizeChildren(vnode, children)

  return vnode
}

function createVNode(
  type: VNodeTypes,
  props: (Data & VNodeProps) | null = null,
  children: unknown = null,
  patchFlag: number = 0 // user provide, not auto-computed
) {
  // resolve shapeFlag, 0 means not match any shape
  const shapeFlag = isString(type)
    ? ShapeFlags.ELEMENT
    : isObject(type)
      ? ShapeFlags.STATEFUL_COMPONENT
      : 0

  return createBaseVNode(type, props, children, shapeFlag, patchFlag)
}

/* ==================== vnode utils ==================== */
function isVNode(value: unknown): value is VNode {
  return value ? value[RuntimeFlags.IS_VNODE] === true : false
}

/**
 * since the comparison involves changes in the type of a `vnode`
 * for the same actual node, `vnode.key` must be compared.
 */
function isSameVNodeType(n1: VNode, n2: VNode): boolean {
  return n1.type === n2.type && n1.key === n2.key
}

export { normalizeVNode, normalizeChildren, createVNode, isVNode, isSameVNodeType }
export type { VNode }
