name: ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint js, ts, md and json files
        run: pnpm run lint

  test:
    name: test (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [unit, unit-jsdom, e2e-jsdom, e2e-browser]
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Prepare puppeteer and playwright
        run: |
          node node_modules/puppeteer/install.mjs
          pnpm exec playwright install chromium

      - name: Run tests for ${{ matrix.project }}
        run: pnpm test --project ${{ matrix.project }} --passWithNoTests
