name: ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [__disable]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    name: lint & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps via lockfile
        run: pnpm install --frozen-lockfile

      - name: Lint js, ts, md and json files
        run: pnpm run lint
